name: natours-db

services:
  mysql:
    image: mysql:8.4.4
    command: ['mysqld', '--mysql-native-password=ON']
    ports:
      - '${MYSQL_DB_PORT}:3306'
    volumes:
      - ./volumes/databases/mysql/data:/var/lib/mysql
      - ./setup/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_DB_PASSWORD}'
      MYSQL_USER: '${MYSQL_DB_USER}'
      MYSQL_PASSWORD: '${MYSQL_DB_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DB_NAME}'
    restart: on-failure

  adminer:
    image: adminer:4.8.1
    ports:
      - '${ADMINER_PORT}:8080'
    depends_on:
      - mysql
